version: '3.8'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/workspaces/laravel
  php-fpm:
    build: ./docker/php-fpm
    user: 1000:1000
    environment:
      - DB_DATABASE=$DB_DATABASE
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=3306
    volumes:
      - .:/workspaces/laravel
  mariadb:
    image: mariadb:10.10.2
    environment:
      - MARIADB_DATABASE=$DB_DATABASE
      - MARIADB_USER=$DB_USERNAME
      - MARIADB_PASSWORD=$DB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$DB_ROOT_PASS
  redis:
    image: redis:7.0.8-alpine
  cli:
    build: ./docker/cli
    volumes:
      - .:/workspaces/laravel
  node:
    image: node:19.6-alpine
    working_dir: /workspaces/laravel
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_CACHE=/workspaces/laravel/.npm #put cache somewhere user has permissions
    ports:
      - 5173:5173
    volumes:
      - .:/workspaces/laravel
    command: /bin/sh -c "npm install && npm run dev --host"
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
