version: '3.8'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
  php-fpm:
    build: ./docker/php-fpm
    environment:
      - DB_DATABASE=$DB_DATABASE
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=3306
    volumes:
      - .:/var/www/html
  mariadb:
    image: mariadb:10.10.2
    environment:
      - MARIADB_DATABASE=$DB_DATABASE
      - MARIADB_USER=$DB_USERNAME
      - MARIADB_PASSWORD=$DB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$DB_ROOT_PASS
  redis:
     image: redis:7.0.8-alpine
