version: '3.8'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
  php-fpm:
    build: ./docker/php-fpm
    user: 82:82 #82/82 is the www-data user/group on alpine images typically
    environment:
      - DB_DATABASE=$DB_DATABASE
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=3306
    volumes:
      - .:/var/www/html
  mariadb:
    image: mariadb:10.10.2
    environment:
      - MARIADB_DATABASE=$DB_DATABASE
      - MARIADB_USER=$DB_USERNAME
      - MARIADB_PASSWORD=$DB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$DB_ROOT_PASS
  redis:
    image: redis:7.0.8-alpine
  cli:
    build: ./docker/cli
    user: 82:82
    volumes:
      - .:/var/www/html
  node:
    image: node:19.6-alpine
    user: 82:82
    working_dir: /home/www-data/app
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_CACHE=/home/www-data/app/.npm #put cache somewhere user has permissions
    ports:
      - 5173:5173
    volumes:
      - .:/home/www-data/app
    command: /bin/sh -c "npm install && npm run dev --host"
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
